/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;
import Lib.Options;
import Services.Database;
import java.awt.CardLayout;
import javax.swing.JComponent;
/**
 *
 * @author Jayvee
 */

public class Main extends javax.swing.JFrame {
    private boolean userExists;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());
    private Options options = new Options(this); // Handler for logic during method listener calls
    private Database database = new Database();
    private String currentLevel;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        
        mainMenu.setMasterPanel(masterPanel);
        optionsPanel1.setMasterPanel(masterPanel);
        optionsPanel1.setOptions(options);
        playPanel1.setMasterPanel(masterPanel);
        levelSelect1.setMasterPanel(masterPanel);
        levelSelect1.setOptions(options);
        levelSelect1.setMain(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        masterPanel = new javax.swing.JPanel();
        mainMenu = new App.Panels.MainMenu();
        optionsPanel1 = new App.Panels.OptionsPanel();
        levelSelect1 = new App.Panels.LevelSelect();
        playPanel1 = new App.Panels.PlayPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SORT IN SYNC");
        setBackground(new java.awt.Color(199, 36, 44));
        setFocusable(false);
        setForeground(java.awt.Color.black);
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        masterPanel.setBackground(new java.awt.Color(199, 36, 44));
        masterPanel.setFocusable(false);
        masterPanel.setLayout(new java.awt.CardLayout());
        masterPanel.add(mainMenu, "mainMenu");
        masterPanel.add(optionsPanel1, "optionsPanel");
        masterPanel.add(levelSelect1, "levelPanel");
        masterPanel.add(playPanel1, "playPanel");

        getContentPane().add(masterPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void launchGame(String levelName, String difficulty) {
        playPanel1.startGame(levelName, difficulty);
        swapCard(masterPanel, "playPanel");
    }
    
    public void swapCard(JComponent comp, String name) {
        CardLayout card = (CardLayout) comp.getLayout();
        card.show(comp, name);
    }
    // TODO: Insert Audio Change
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private App.Panels.LevelSelect levelSelect1;
    private App.Panels.MainMenu mainMenu;
    private javax.swing.JPanel masterPanel;
    private App.Panels.OptionsPanel optionsPanel1;
    private App.Panels.PlayPanel playPanel1;
    // End of variables declaration//GEN-END:variables
}
