/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package App.Panels;
import App.Panels.PlayPanel;
import App.Components.CustomLabel;
import App.Components.CustomRadioButton;
import App.Main;
import Lib.Options;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseEvent;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jayvee
 */
public class LevelSelect extends javax.swing.JPanel {
    private JComponent masterPanel;
    private Main main;
    private Options options;
    private String selectedLevel;
    
    /**
     * Creates new form LevelSelect
     */
    public LevelSelect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGroup1 = new javax.swing.ButtonGroup();
        topPanel = new javax.swing.JPanel();
        backBtn = new App.Components.CustomButton();
        controlsBtn = new App.Components.CustomButton();
        customButton1 = new App.Components.CustomButton();
        mainPanel = new javax.swing.JPanel();
        leaderboardPanel = new javax.swing.JPanel();
        leaderboardTitle = new javax.swing.JPanel();
        customLabel4 = new App.Components.CustomLabel();
        leaderboardNames = new javax.swing.JPanel();
        top1 = new App.Components.CustomLabel();
        top2 = new App.Components.CustomLabel();
        top3 = new App.Components.CustomLabel();
        top4 = new App.Components.CustomLabel();
        top5 = new App.Components.CustomLabel();
        top6 = new App.Components.CustomLabel();
        top7 = new App.Components.CustomLabel();
        top8 = new App.Components.CustomLabel();
        top9 = new App.Components.CustomLabel();
        top10 = new App.Components.CustomLabel();
        levelsPanel = new javax.swing.JPanel();
        level1 = new javax.swing.JPanel();
        customLabel1 = new App.Components.CustomLabel();
        level2 = new javax.swing.JPanel();
        customLabel2 = new App.Components.CustomLabel();
        level3 = new javax.swing.JPanel();
        customLabel3 = new App.Components.CustomLabel();
        level4 = new javax.swing.JPanel();
        customLabel5 = new App.Components.CustomLabel();
        level5 = new javax.swing.JPanel();
        customLabel6 = new App.Components.CustomLabel();
        settingsPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        easyRB = new App.Components.CustomRadioButton();
        normalRB = new App.Components.CustomRadioButton();
        hardRB = new App.Components.CustomRadioButton();
        playBtn = new App.Components.CustomButton();

        setBackground(new java.awt.Color(199, 36, 44));
        setFocusable(false);
        setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(199, 36, 44));
        topPanel.setFocusable(false);
        topPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        backBtn.setText("BACK");
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backBtn.addActionListener(this::backPerformed);
        topPanel.add(backBtn);

        controlsBtn.setText("CONTROLS");
        controlsBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        controlsBtn.addActionListener(this::controlsBtnActionPerformed);
        topPanel.add(controlsBtn);

        customButton1.setText("HELP");
        customButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customButton1.addActionListener(this::customButton1ActionPerformed);
        topPanel.add(customButton1);

        add(topPanel, java.awt.BorderLayout.NORTH);

        mainPanel.setBackground(new java.awt.Color(199, 36, 44));
        mainPanel.setFocusable(false);
        mainPanel.setLayout(new java.awt.GridLayout(1, 3));

        leaderboardPanel.setBackground(new java.awt.Color(199, 36, 44));
        leaderboardPanel.setLayout(new java.awt.BorderLayout());

        leaderboardTitle.setBackground(new java.awt.Color(199, 36, 44));

        customLabel4.setText("LEADEARBOARD TOP 10");
        customLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        leaderboardTitle.add(customLabel4);

        leaderboardPanel.add(leaderboardTitle, java.awt.BorderLayout.NORTH);

        leaderboardNames.setBackground(new java.awt.Color(199, 36, 44));
        leaderboardNames.setLayout(new java.awt.GridLayout(10, 1));

        top1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        top1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        leaderboardNames.add(top1);

        top2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        top2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        leaderboardNames.add(top2);

        top3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        top3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        leaderboardNames.add(top3);

        top4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        top4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        leaderboardNames.add(top4);

        top5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        top5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        leaderboardNames.add(top5);

        top6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        top6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        leaderboardNames.add(top6);

        top7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        top7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        leaderboardNames.add(top7);

        top8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        top8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        leaderboardNames.add(top8);

        top9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        top9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        leaderboardNames.add(top9);

        top10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        top10.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        leaderboardNames.add(top10);

        leaderboardPanel.add(leaderboardNames, java.awt.BorderLayout.CENTER);

        mainPanel.add(leaderboardPanel);

        levelsPanel.setBackground(new java.awt.Color(199, 36, 44));
        levelsPanel.setLayout(new java.awt.GridLayout(5, 1));

        level1.setBackground(new java.awt.Color(199, 36, 44));
        level1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelHoverMouse(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverRemovedMouse(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                levelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                levelMouseRelease(evt);
            }
        });

        customLabel1.setText("Canon");
        level1.add(customLabel1);

        levelsPanel.add(level1);

        level2.setBackground(new java.awt.Color(199, 36, 44));
        level2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelHoverMouse(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverRemovedMouse(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                levelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                levelMouseRelease(evt);
            }
        });

        customLabel2.setText("CanCan");
        level2.add(customLabel2);

        levelsPanel.add(level2);

        level3.setBackground(new java.awt.Color(199, 36, 44));
        level3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelHoverMouse(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverRemovedMouse(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                levelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                levelMouseRelease(evt);
            }
        });

        customLabel3.setText("TwoTigers");
        level3.add(customLabel3);

        levelsPanel.add(level3);

        level4.setBackground(new java.awt.Color(199, 36, 44));
        level4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelHoverMouse(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverRemovedMouse(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                levelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                levelMouseRelease(evt);
            }
        });

        customLabel5.setText("Spring");
        level4.add(customLabel5);

        levelsPanel.add(level4);

        level5.setBackground(new java.awt.Color(199, 36, 44));
        level5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelHoverMouse(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverRemovedMouse(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                levelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                levelMouseRelease(evt);
            }
        });

        customLabel6.setText("BeyerNo8");
        level5.add(customLabel6);

        levelsPanel.add(level5);

        mainPanel.add(levelsPanel);

        settingsPanel.setBackground(new java.awt.Color(199, 36, 44));

        jPanel1.setBackground(new java.awt.Color(199, 36, 44));
        jPanel1.setLayout(new java.awt.GridLayout(3, 1, 0, 5));

        bGroup1.add(easyRB);
        easyRB.setText("Easy");
        easyRB.setEnabled(false);
        easyRB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        easyRB.addItemListener(this::difficultyRBItemStateChanged);
        jPanel1.add(easyRB);

        bGroup1.add(normalRB);
        normalRB.setText("Medium");
        normalRB.setEnabled(false);
        normalRB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        normalRB.addItemListener(this::difficultyRBItemStateChanged);
        jPanel1.add(normalRB);

        bGroup1.add(hardRB);
        hardRB.setText("Hard");
        hardRB.setEnabled(false);
        hardRB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hardRB.addItemListener(this::difficultyRBItemStateChanged);
        jPanel1.add(hardRB);

        settingsPanel.add(jPanel1);

        playBtn.setText("PLAY");
        playBtn.setEnabled(false);
        playBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        playBtn.addActionListener(this::playButtonPressed);
        settingsPanel.add(playBtn);

        mainPanel.add(settingsPanel);

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public void setMasterPanel(JComponent masterPanel) {
        this.masterPanel = masterPanel;
    }

    public void setOptions(Options options) {
        this.options = options;
    }
    
    public void setMain(Main main) {
        this.main = main;
    }
    
    private void backPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backPerformed
        if (this.masterPanel == null) return; // Master Panel was not set
        resetComponents();
        this.swapCard(masterPanel, "mainMenu");
    }//GEN-LAST:event_backPerformed

    private void playButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonPressed
        if (this.masterPanel == null || this.main == null) return;
   
        String selectedDifficulty = "Normal"; 
        for (Component comp : jPanel1.getComponents()) {
            if (comp instanceof CustomRadioButton) {
                if (((CustomRadioButton) comp).isSelected()) {
                    selectedDifficulty = ((CustomRadioButton) comp).getText();
                }
            }
        }
        
        resetComponents();
        main.launchGame(selectedLevel, selectedDifficulty);
    }//GEN-LAST:event_playButtonPressed

    /*
        Mouse events basically just change the background color of the panel and change
        the current selected level so once they select a difficulty and a level, they
        would be able tom play that level.
    */
    private void panelHoverMouse(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHoverMouse
        // TODO add your handling code here:
        JPanel comp = (JPanel) evt.getComponent();
        Color clr = options.getBgColor();
        comp.setBackground(options.computeHoverColor(clr));
    }//GEN-LAST:event_panelHoverMouse

    private void hoverRemovedMouse(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoverRemovedMouse
        // TODO add your handling code here:
        JPanel comp = (JPanel) evt.getComponent();
        Color clr = options.getBgColor();
        comp.setBackground(clr);
    }//GEN-LAST:event_hoverRemovedMouse

    private void levelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_levelMousePressed
        // TODO add your handling code here:
        panelIsClicked(evt); // 
        if (evt.getSource() == level1) {
            selectedLevel = extractText(level1);
        } else if (evt.getSource() == level2) { 
            selectedLevel = extractText(level2);
        } else if (evt.getSource() == level3) {
            selectedLevel = extractText(level3);
        } else if (evt.getSource() == level4) {
            selectedLevel = extractText(level4);
        } else if (evt.getSource() == level5) {
            selectedLevel = extractText(level5);
        }
        
        enableComponents(true);
    }//GEN-LAST:event_levelMousePressed
        
    private void levelMouseRelease(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_levelMouseRelease
        // TODO add your handling code here:
        JPanel panel = (JPanel) evt.getComponent();
        Color clr = options.getBgColor();
        clr = options.computeHoverColor(clr);
        panel.setBackground(clr);
    }//GEN-LAST:event_levelMouseRelease

    private void controlsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlsBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(masterPanel, "Left Arrow Key -> Biodegradable\n"
                + "Down Arrow Key -> Recyclable\n"
                + "Up Arrow Key -> Hazardous\n"
                + "Right Arrow Key -> Residual / General Waste", "Controls", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_controlsBtnActionPerformed

    private void customButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton1ActionPerformed
        // TODO add your handling code here:
        // TODO: add code here to show what types of keys you need to press for what
        JOptionPane.showMessageDialog(masterPanel, "Add content later.", "Help", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_customButton1ActionPerformed

    private void difficultyRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_difficultyRBItemStateChanged
        // TODO add your handling code here:
        enableComponent(playBtn, true);
    }//GEN-LAST:event_difficultyRBItemStateChanged

    private void resetComponents() {
        bGroup1.clearSelection();
        enableComponents(false);
        enableComponent(playBtn, false);
    }
    
    private void panelIsClicked(MouseEvent evt) {
        JPanel panel = (JPanel) evt.getComponent();
        Color clr = options.getBgColor();
        for (int i = 0; i < 2; i++) {
            clr = options.computeHoverColor(clr);
        }
        
        panel.setBackground(clr);
    }
    
    // Enables or disables button
    private void enableComponents(boolean bool) {
        for (Component comp : jPanel1.getComponents()) {
            if (comp instanceof CustomRadioButton) {
                ((CustomRadioButton) comp).setEnabled(bool);
            }
        }
    }
    
    public void enableComponent(JComponent comp, boolean bool) {
        comp.setEnabled(bool);
    }
    
    // Get Text of the JLabel
    private String extractText(JComponent component) {
        for (Component comp : component.getComponents()) {
           if (comp instanceof CustomLabel) {
               String txt = ((JLabel) comp).getText();
               return txt;
           } 
        }
        return null;
    }
    
    private void swapCard(JComponent comp, String name) {
        CardLayout card = (CardLayout) comp.getLayout();
        card.show(comp, name);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGroup1;
    private App.Components.CustomButton backBtn;
    private App.Components.CustomButton controlsBtn;
    private App.Components.CustomButton customButton1;
    private App.Components.CustomLabel customLabel1;
    private App.Components.CustomLabel customLabel2;
    private App.Components.CustomLabel customLabel3;
    private App.Components.CustomLabel customLabel4;
    private App.Components.CustomLabel customLabel5;
    private App.Components.CustomLabel customLabel6;
    private App.Components.CustomRadioButton easyRB;
    private App.Components.CustomRadioButton hardRB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel leaderboardNames;
    private javax.swing.JPanel leaderboardPanel;
    private javax.swing.JPanel leaderboardTitle;
    private javax.swing.JPanel level1;
    private javax.swing.JPanel level2;
    private javax.swing.JPanel level3;
    private javax.swing.JPanel level4;
    private javax.swing.JPanel level5;
    private javax.swing.JPanel levelsPanel;
    private javax.swing.JPanel mainPanel;
    private App.Components.CustomRadioButton normalRB;
    private App.Components.CustomButton playBtn;
    private javax.swing.JPanel settingsPanel;
    private App.Components.CustomLabel top1;
    private App.Components.CustomLabel top10;
    private App.Components.CustomLabel top2;
    private App.Components.CustomLabel top3;
    private App.Components.CustomLabel top4;
    private App.Components.CustomLabel top5;
    private App.Components.CustomLabel top6;
    private App.Components.CustomLabel top7;
    private App.Components.CustomLabel top8;
    private App.Components.CustomLabel top9;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
