/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package App.Panels;

import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import Services.Database;
import Lib.Options;
import java.awt.CardLayout;
import java.beans.Beans;
import javax.swing.JComponent;
/**
 *
 * @author Jayvee
 */
public class MainMenu extends javax.swing.JPanel {
    private Database database;
    private JComponent masterPanel;
    private Options options; // Set by Main; used to save settings for the logged-in user
    private static final System.Logger LOG = System.getLogger(MainMenu.class.getName());
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        
        if (!Beans.isDesignTime()) {
            database = new Database();
        }
    }

    public void setMasterPanel(JComponent masterPanel) {
        this.masterPanel = masterPanel;
    }
    
    public void setOptions(Options options) {
        this.options = options;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        customLabel1 = new App.Components.CustomLabel();
        menuButtonsPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        playBtn = new App.Components.CustomButton();
        optionsBtn = new App.Components.CustomButton();
        exitBtn = new App.Components.CustomButton();
        bottomPanel = new javax.swing.JPanel();
        loggedOut = new javax.swing.JPanel();
        loginBtn = new App.Components.CustomButton();
        signUpBtn = new App.Components.CustomButton();
        loggedIn = new javax.swing.JPanel();
        userText = new App.Components.CustomLabel();
        signOutBtn = new App.Components.CustomButton();

        setLayout(new java.awt.BorderLayout());

        mainPanel.setBackground(new java.awt.Color(199, 36, 44));
        mainPanel.setToolTipText("");
        mainPanel.setFocusable(false);
        mainPanel.setLayout(new java.awt.GridLayout(2, 1));

        titlePanel.setBackground(new java.awt.Color(199, 36, 44));
        titlePanel.setLayout(new java.awt.BorderLayout());

        customLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Menu Screen/Classic/Logo.png"))); // NOI18N
        customLabel1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        titlePanel.add(customLabel1, java.awt.BorderLayout.CENTER);

        mainPanel.add(titlePanel);

        menuButtonsPanel.setBackground(new java.awt.Color(199, 36, 44));

        buttonPanel.setBackground(new java.awt.Color(199, 36, 44));
        buttonPanel.setLayout(new java.awt.GridLayout(4, 1, 10, 10));

        playBtn.setText("PLAY");
        playBtn.setFocusable(false);
        playBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        playBtn.addActionListener(this::playPerformed);
        buttonPanel.add(playBtn);

        optionsBtn.setText("OPTIONS");
        optionsBtn.setFocusable(false);
        optionsBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        optionsBtn.addActionListener(this::optionPerformed);
        buttonPanel.add(optionsBtn);

        exitBtn.setText("EXIT");
        exitBtn.setFocusable(false);
        exitBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        exitBtn.addActionListener(this::exitPerformed);
        buttonPanel.add(exitBtn);

        bottomPanel.setBackground(new java.awt.Color(199, 36, 44));
        bottomPanel.setLayout(new java.awt.CardLayout());

        loggedOut.setBackground(new java.awt.Color(199, 36, 44));
        loggedOut.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        loginBtn.setText("LOGIN");
        loginBtn.setFocusable(false);
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginBtn.addActionListener(this::loginActionPerformed);
        loggedOut.add(loginBtn);

        signUpBtn.setText("SIGN UP");
        signUpBtn.setFocusable(false);
        signUpBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signUpBtn.addActionListener(this::loginActionPerformed);
        loggedOut.add(signUpBtn);

        bottomPanel.add(loggedOut, "loggedOut");

        loggedIn.setBackground(new java.awt.Color(199, 36, 44));
        loggedIn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        userText.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        loggedIn.add(userText);

        signOutBtn.setText("SIGN OUT");
        signOutBtn.setFocusable(false);
        signOutBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signOutBtn.addActionListener(this::signoutPerformed);
        loggedIn.add(signOutBtn);

        bottomPanel.add(loggedIn, "loggedIn");

        buttonPanel.add(bottomPanel);

        menuButtonsPanel.add(buttonPanel);

        mainPanel.add(menuButtonsPanel);

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        JTextField username = new JTextField();
        JPasswordField password = new JPasswordField();
        String pass, user;
 
        Object[] comp = {
            "Username:", username,
            "Password:", password
        };
 
        if (evt.getSource() == loginBtn) {
            System.out.println("[Notice]: Attempting to login to an account.");
            int option = JOptionPane.showConfirmDialog(null, comp, "Login", JOptionPane.OK_CANCEL_OPTION);
            if (option == JOptionPane.OK_OPTION) {
                user = username.getText();
                pass = new String(password.getPassword());
 
                if (database.validateLogin(user, pass)) {
                    System.out.println("[Success]: Logged in as: " + user);
                    userText.setText("Logged in as: "+ user);
                    if (options != null) {
                        options.setCurrentUser(database.getUserId(user)); // Settings now save for this user
                    }
                    // TODO: once a "currently logged in as" label exists on this
                    // panel, set its text here (e.g. currentUserText.setText("Logged in as: " + user);)
                    this.swapCard(bottomPanel, "loggedIn");
                } else {
                    System.out.println("[Error]: Could not successfully login.");
                    JOptionPane.showMessageDialog(null, "Invalid username or password", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }
        } else if (evt.getSource() == signUpBtn) {
            System.out.println("[Notice]: Creating a new account.");
            int option = JOptionPane.showConfirmDialog(null, comp, "Sign Up", JOptionPane.OK_CANCEL_OPTION);
 
            if (option == JOptionPane.OK_OPTION) {
                user = username.getText();
                pass = new String(password.getPassword());
 
                if (database.registerUser(user, pass)) {
                    System.out.println("[Success]: Account created for: " + user);
                    // TODO: auto-login or prompt the user to log in now that the account exists
                } else {
                    System.out.println("[Error]: Failed to create account.");
                    JOptionPane.showMessageDialog(null, "User already taken or invalid input.", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_loginActionPerformed

    private void signoutPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutPerformed
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?", "Log out", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            System.out.println("[Notice]: Signed out.");
            userText.setText("");
            if (options != null) {
                options.setCurrentUser(Options.GUEST); // Stop saving settings for the old user
            }
            // TODO: clear the "currently logged in as" label here too, once it exists
            this.swapCard(bottomPanel, "loggedOut");
        }
    }//GEN-LAST:event_signoutPerformed

    private void exitPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitPerformed
        System.out.println("[Exit]: Program has been terminated");
        System.exit(0);
    }//GEN-LAST:event_exitPerformed

    private void optionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionPerformed
        if (masterPanel == null) {
            System.out.println("[Error]: masterPanel was never set on MainMenu - call setMasterPanel() from Main's constructor.");
            return;
        }
        System.out.println("[Changed-Panel]: Main Menu -> Options");
        this.swapCard(masterPanel, "optionsPanel");
    }//GEN-LAST:event_optionPerformed

    private void playPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playPerformed
        if (masterPanel == null) {
            System.out.println("[Error]: masterPanel was never set on MainMenu - call setMasterPanel() from Main's constructor.");
            return;
        }
        System.out.println("[Changed-Panel]: Main Menu -> Level Select");
        this.swapCard(masterPanel, "levelPanel");
    }//GEN-LAST:event_playPerformed

    private void swapCard(JComponent comp, String name) {
        CardLayout card = (CardLayout) comp.getLayout();
        card.show(comp, name);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel buttonPanel;
    private App.Components.CustomLabel customLabel1;
    private App.Components.CustomButton exitBtn;
    private javax.swing.JPanel loggedIn;
    private javax.swing.JPanel loggedOut;
    private App.Components.CustomButton loginBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuButtonsPanel;
    private App.Components.CustomButton optionsBtn;
    private App.Components.CustomButton playBtn;
    private App.Components.CustomButton signOutBtn;
    private App.Components.CustomButton signUpBtn;
    private javax.swing.JPanel titlePanel;
    private App.Components.CustomLabel userText;
    // End of variables declaration//GEN-END:variables
}
