/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package App.Panels;

import Lib.Options;
import Lib.Theme;
import java.awt.CardLayout;
import javax.swing.JComponent;

/**
 *
 * @author Jayvee
 */
public class OptionsPanel extends javax.swing.JPanel {
    private static final String[] RESOLUTIONS = {
        "Select A Resolution",
        "1280x720",
        "1024x768",
        "960x540",
        "800x600",
        "640x480"
    };
    
    private JComponent masterPanel;
    private Options options;
    
    /**
     * Creates new form OptionsPanel
     */
    public OptionsPanel() {
        initComponents();
        for (String res : RESOLUTIONS) {
            resolutionDropdown.addItem(res);
        }
        themeDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(Theme.labels()));
    }

    public void setMasterPanel(JComponent masterPanel) {
        this.masterPanel = masterPanel;
    }
    
    public void setOptions(Options options) {
        this.options = options;
        musicSlider.setValue(options.getVolume());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsPanel = new javax.swing.JTabbedPane();
        audioPanel = new javax.swing.JPanel();
        musicText = new App.Components.CustomLabel();
        musicSlider = new App.Components.CustomSlider();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        visualPanel = new javax.swing.JPanel();
        resolutionText = new App.Components.CustomLabel();
        resolutionPanel = new javax.swing.JPanel();
        resolutionDropdown = new App.Components.CustomDropdown();
        themeText = new App.Components.CustomLabel();
        themePanel = new javax.swing.JPanel();
        themeDropdown = new App.Components.CustomDropdown();
        fontText = new App.Components.CustomLabel();
        fontPanel = new javax.swing.JPanel();
        fontDropdown = new App.Components.CustomDropdown();
        bottomPanel = new javax.swing.JPanel();
        cancelBtn = new App.Components.CustomButton();
        saveBtn = new App.Components.CustomButton();

        setBackground(new java.awt.Color(199, 36, 44));
        setLayout(new java.awt.BorderLayout());

        settingsPanel.setBackground(new java.awt.Color(199, 36, 44));
        settingsPanel.setForeground(new java.awt.Color(241, 212, 45));

        audioPanel.setBackground(new java.awt.Color(199, 36, 44));
        audioPanel.setLayout(new java.awt.GridLayout(3, 2, 15, 12));

        musicText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        musicText.setText("Music Volume");
        musicText.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        audioPanel.add(musicText);
        audioPanel.add(musicSlider);

        jPanel1.setBackground(new java.awt.Color(199, 36, 44));
        audioPanel.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(199, 36, 44));
        audioPanel.add(jPanel2);

        settingsPanel.addTab("AUDIO", audioPanel);

        visualPanel.setBackground(new java.awt.Color(199, 36, 44));
        visualPanel.setLayout(new java.awt.GridLayout(3, 2));

        resolutionText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        resolutionText.setText("Resolution");
        visualPanel.add(resolutionText);

        resolutionPanel.setBackground(new java.awt.Color(199, 36, 44));
        resolutionPanel.add(resolutionDropdown);

        visualPanel.add(resolutionPanel);

        themeText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        themeText.setText("Theme");
        visualPanel.add(themeText);

        themePanel.setBackground(new java.awt.Color(199, 36, 44));

        themeDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Light", "Dark" }));
        themePanel.add(themeDropdown);

        visualPanel.add(themePanel);

        fontText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fontText.setText("Font");
        visualPanel.add(fontText);

        fontPanel.setBackground(new java.awt.Color(199, 36, 44));

        fontDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SansSerif", "Monospaced" }));
        fontPanel.add(fontDropdown);

        visualPanel.add(fontPanel);

        settingsPanel.addTab("VISUAL", visualPanel);

        add(settingsPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setBackground(new java.awt.Color(199, 36, 44));
        bottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        cancelBtn.setText("CANCEL");
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelBtn.addActionListener(this::optionsPerformed);
        bottomPanel.add(cancelBtn);

        saveBtn.setText("SAVE");
        saveBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveBtn.addActionListener(this::optionsPerformed);
        bottomPanel.add(saveBtn);

        add(bottomPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void optionsPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsPerformed
        if (masterPanel == null) {
            System.out.println("[Error]: masterPanel was never set on OptionsPanel - call setMasterPanel() from Main's constructor.");
            return;
        }
 
        if (evt.getSource() == cancelBtn) {
            System.out.println("[Changed-Panel]: Options -> Main Menu");
            this.swapCard(masterPanel, "mainMenu");
        } else if (evt.getSource() == saveBtn) {
            if (options == null) {
                System.out.println("[Error]: options was never set on OptionsPanel - call setOptions() from Main's constructor.");
                return;
            }
            System.out.println("[Update]: Saving option configuration");
 
            options.changeTheme(themeDropdown);
            options.changeResolution(resolutionDropdown);
            options.changeFont(fontDropdown);
            options.changeVolume(musicSlider.getValue());
            
            this.swapCard(masterPanel, "mainMenu");
            System.out.println("[Changed-Panel]: Options -> Main Menu");
        }
    }//GEN-LAST:event_optionsPerformed

    private void swapCard(JComponent comp, String name) {
        CardLayout card = (CardLayout) comp.getLayout();
        card.show(comp, name);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel audioPanel;
    private javax.swing.JPanel bottomPanel;
    private App.Components.CustomButton cancelBtn;
    private App.Components.CustomDropdown fontDropdown;
    private javax.swing.JPanel fontPanel;
    private App.Components.CustomLabel fontText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private App.Components.CustomSlider musicSlider;
    private App.Components.CustomLabel musicText;
    private App.Components.CustomDropdown resolutionDropdown;
    private javax.swing.JPanel resolutionPanel;
    private App.Components.CustomLabel resolutionText;
    private App.Components.CustomButton saveBtn;
    private javax.swing.JTabbedPane settingsPanel;
    private App.Components.CustomDropdown themeDropdown;
    private javax.swing.JPanel themePanel;
    private App.Components.CustomLabel themeText;
    private javax.swing.JPanel visualPanel;
    // End of variables declaration//GEN-END:variables
}
